[package]
name = "aoc"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "0.20.5"
regex = "1"
reqwest = "0.9.5"

[profile.release]
# Enable debug information in release builds.
debug = true
